### ISSUE TITLE
Permettere ai moderatori di sezioni di gestire operazioni aggiuntive sui topic

### ISSUE THREAD

**Issue by theCrius** [netgamers-forum/discourse-category-mod-enhancer#1]
L'idea che mi sono fatto e' che il valore viene semplicemente nascosto (da verificare se via css o a livello di controller) in base al ruolo. La cosa necessaria e' far si che questa opzione sia visibile per i moderatori di sezione. La funzionalita' resta la stessa.

![image](https://user-images.githubusercontent.com/2202141/229199171-09aa2b76-b033-430d-865d-0be9a0f6b4a2.png)

Queste quattro opzioni, dovrebbero essere rese visibili quando i mod di categoria agiscono nella loro categoria.

**Comment by DanieleMancini** [comment]
@theCrius in locale ho promosso un utente a moderatore e queste opzioni di moderazione le vedo.
![image](https://user-images.githubusercontent.com/12233062/229357780-e1e4ecc9-b864-4362-9215-64f3c44a60aa.png)

ma di discourse non ci capisco una sega asd, mi puoi dire come riprodurlo ?

**Comment by theCrius** [comment]
Crea un gruppo, chiamalo come vuoi, mettiamo `general-moderators`

Assegnaci un utente che **non** sia gia' `admin` o `moderator`.

Poi vai nella categoria `General` per esempio, apri i settings cliccando sull'icona della chiave inglese quando sei nella lista dei topic della categoria.

Apri il tab "settings".... dei settings (cazzo di geni) e dovresti vedere una textbox. Scrivi il nome del gruppo che hai creato per assegnarlo come category moderators.

![image](https://user-images.githubusercontent.com/2202141/229360050-5948e50a-8eca-4530-bb61-7dafae31640f.png)


Poi impersona quell'utente che hai infilato nel gruppo, andando nel suo profilo da admin, e cliccando in basso sul pulsante "impersonate" e vedrai che in quella categoria hai delle opzioni ma veramente limitate e fuori da quella categoria non hai accesso a moderazione.

**Comment by DanieleMancini** [comment]
thanks, ora provo.

**Comment by DanieleMancini** [comment]
per eventuali futuri volenterosi: prima bisogna attivare questa opzione 
![image](https://user-images.githubusercontent.com/12233062/229365172-d6677db0-d989-4353-9cdc-6bd4fde211f1.png)

**Comment by DanieleMancini** [comment]
allora ci sono andato abbastanza cauto non capendo del tutto le differenze fra 'staff'  'moderator' e 'category_moderator'
![image](https://user-images.githubusercontent.com/12233062/229368186-d578ceec-bc78-4ca0-9db3-860ef13e4d91.png)

ho aggiunto in or details.get("can_moderate_category") su i pulsanti in questione (abbastanza una zozzata)
![image](https://user-images.githubusercontent.com/12233062/229368255-8c5888d6-032d-40e0-b33f-45a2104c49f9.png)

una soluzione migliore sarebbe dare ai category moderator la possibilita di 'canManageTopic'  (in pratica nelle categorie dove sono mod posso fare tutto quello di un moderator normale)

c'è un piccolo problema: se il topic fa parte di due categorie vieni presa in considerazione solo l'ultima:
in particolare:
![image](https://user-images.githubusercontent.com/12233062/229368471-29ef4922-5f3a-4482-92d5-310da05876b9.png)
oltre ad essere chiamata 800 volte riporta solo l'ultima categoria del topic

**Comment by theCrius** [comment]
In teoria un topic puo' far parte sempre solo di una categoria comunque
forse e' un array perche' boh, ma quantomeno nel nostro caso, non esiste che un topic abbia due categorie.

L'unica cosa multipla che puo' avere sono tags.

**Comment by theCrius** [comment]
La logica finale comunque, per tutte queste issue, deve essere:

- L'utente appartiene alla categoria assegnata come moderatore di questa sezione
- Sta agendo su questa sezione/topic di questa sezione

E ovviamente un plugin, non andiamo a modificare direttamente i file di discourse (ma suppongo stessi vedendo per capire come diamine funziona)

**Comment by DanieleMancini** [comment]
chiaro, appena ho un po' di tempo studierò come traslare tutto in un plugin.
