### ISSUE TITLE
Permettere ai mod di sezione di spostare un intero topic in un'altra sezione

### ISSUE THREAD

**Issue by theCrius** [netgamers-forum/discourse-category-mod-enhancer#5]
Bisogna attivare la visualizzazione delle bulk action perche' il move topic su singolo topic non esiste a quanto pare

![image](https://user-images.githubusercontent.com/2202141/229201564-b5a6e1d7-a073-478b-b15b-c82492754801.png)

![image](https://user-images.githubusercontent.com/2202141/229201650-09d29b9a-e789-477f-8111-330da4387917.png)

Da assicurasi poi che le azioni possibili funzionino

![image](https://user-images.githubusercontent.com/2202141/229201703-583e742a-4dc7-4e34-896a-5b7188f98c2a.png)

**Comment by DanieleMancini** [comment]
![image](https://github.com/netgamers-forum/discourse-category-mod-enhancer/assets/12233062/e1bc3970-0179-4b0f-b000-5633aad9be5a)

stavo un po impazzendo per queste bulk actions per i mod di categoria, ma poi mi sono accorto che nel singolo thread c'e questa opzione per cambiare la categoria, non capisco se è la stessa cosa.

**Comment by theCrius** [comment]
Ne abbiamo parlato in call ma giusto per metterla per scritto come riferimento futuro:

lasciamo stare le bulk actions
si quella funzione e' la stessa cosa per singolo topic MA al momento viene nascosta da questo component https://github.com/netgamers-forum/discourse-restrict-edit-category.

Bisognera' trovare un modo per includere i mod di categoria nella whitelist assieme ad admin e moderators.
