### ISSUE TITLE
Replace logic of `is_staff` in Guardian.rb

### ISSUE THREAD

**Issue by theCrius** [netgamers-forum/discourse-category-mod-enhancer#9]
Vedi https://github.com/netgamers-forum/discourse-category-mod-enhancer/issues/6#issuecomment-1567499763

Sembra che tutte le funzioni di moderazione siano basate su is_staff quindi un approccio valido e' modificare la funzione che determina se un utente e' "staff" per includere quelli che sono moderatori di sezione.

Quindi in riga `108`:

```
def is_staff?(category = false)
  @user.staff?
end
```

Si puo' tentare un refactor brutale del tipo:

```
def is_staff?(category = false)
  self.is_admin? || self.is_moderator? || self.is_category_group_moderator?(category)
end
```

**Comment by theCrius** [comment]
use https://kleinfreund.de/how-to-create-a-discourse-plugin/ as guide

**Comment by DanieleMancini** [comment]
cosi a naso non credo sia l'approccio migliore,anche perchè andrebbe modificata ogni azione che richiama is_staff? passando anche la categoria, 
l'approccio che sto valutando è quello di decorare attraverso un plugin il widget già esistente topic-admin-menu.
e andare a modificare il guardian già esistente CategoryGuardian

anzi ancora meglio sarebbe modificare il topicguardian abilitando le azioni se sei mod di quella categoria
